package com.rootscare.ui.physiotherapy.bookingappointment

import com.rootscare.ui.base.BaseViewModel
import com.rootscare.ui.physiotherapy.FragmentSeeAllPhysiotherapyListingNavigator

class FragmentPhysiotherapyBookingAppointmentViewModel : BaseViewModel<FragmentPhysiotherapyBookingAppointmentNavigator>(){
}